tags:
  TechnicalOwner: "Ivan Gonzalez Berasategui"
  ATNR: "0000000"
resource_groups:
  - name: rg-igb-testlab-pro
    region: westeurope
  - name: rg-igb-testlab-pro2
    region: westeurope
  - name: rg-igb-testlab-pro3
    region: westeurope